name: Free VLESS Tunnel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download sing-box
        run: |
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.9.0/sing-box-1.9.0-linux-amd64.tar.gz
          tar -xvzf sing-box.tar.gz
          chmod +x sing-box*/sing-box
          mv sing-box*/sing-box sing-box

      - name: Create config.json
        run: |
          echo '{
            "log": {
              "level": "info"
            },
            "inbounds": [{
              "type": "vless",
              "listen": "::",
              "listen_port": 443,
              "users": [{
                "uuid": "00000000-0000-0000-0000-000000000000",
                "flow": "xtls-rprx-vision"
              }],
              "tls": {
                "enabled": true,
                "server_name": "www.microsoft.com",
                "reality": {
                  "enabled": true,
                  "handshake": {
                    "server": "www.microsoft.com",
                    "server_port": 443
                  },
                  "private_key": "U8fh-KbpQEGZ1Aq4RoSl0_C9fCgZsy0PZ5rNQ38X2l8",
                  "short_id": ["12345678"]
                }
              }
            }],
            "outbounds": [{
              "type": "direct"
            }]
          }' > config.json

      - name: Start VLESS Server
        run: |
          nohup ./sing-box run -c config.json &

      - name: Show VLESS Link
        run: |
          echo 'vless://00000000-0000-0000-0000-000000000000@github.com:443?encryption=none&flow=xtls-rprx-vision&security=reality&sni=www.microsoft.com&fp=random&type=grpc&serviceName=443#FreeTunnel'
